IsSelected = false;
UnitState = UNIT_STATE_CREATED;
MoveLocationX = -100;
MoveLocationY = -100;
MoveSpeed = 0;
UnitHealth = argument0;
UnitScore = argument1;
UnitXP = argument2;
UnitRange = argument3;
UnitAttack = argument4;
UnitRangedAttack = argument5;
UnitMagicAttack = argument6;
UnitArmour = argument7;
UnitRangedArmour = argument8;
UnitMagicArmour = argument9;
UnitCreatureArmour = argument10;
MoveRangeFrontBack = argument11;
MoveRangeUpDown = argument12;
MoveRangeDiagonal = argument13;
CreationDelay = 0;
ActionDelay = 0;

//UnitCreated(25,5,5,1,10,0,0,5,5,0,5,2,2,1);
